CREATE TABLE driver_verification (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
	middle_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
	gender VARCHAR(50) NOT NULL,
	referral_code VARCHAR(50) NOT NULL,
	Driver_type VARCHAR(50) NOT NULL,
    driver_license_number VARCHAR(50) NOT NULL UNIQUE,
    driver_license_expiry DATE NOT NULL,
	vehicle_manufacturer VARCHAR(50) NOT NULL,
	vehicle_model VARCHAR(50) NOT NULL,
	vehicle_year VARCHAR(50) NOT NULL,
	vehicle_color VARCHAR(50) NOT NULL,
    profile_photo BYTEA,
    car_photo_inner BYTEA,
	car_photo_outter BYTEA,
    driver_license_document BYTEA,
	vehicle_license_certification BYTEA,
	certification_of_roadworthiness BYTEA,
	issued_id BYTEA,
	proof_of_ownership BYTEA,
    verification_status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);